server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    jaas:
      login-module:

springdoc:
  api-docs:
    path: /api-docs-json
  swagger-ui:
    path: /api-docs
